# Generated by Django 4.2.4 on 2023-08-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_code",
                    models.CharField(
                        max_length=3, verbose_name="Символьное обозначение"
                    ),
                ),
                ("name", models.CharField(max_length=35, verbose_name="Наименование")),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
            },
        ),
    ]
