# Generated by Django 4.2.4 on 2023-08-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencydirectory",
            name="value",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=9, verbose_name="Значение"
            ),
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRateDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_app.currencydirectory",
                    ),
                ),
            ],
        ),
    ]
