# Generated by Django 4.2.4 on 2023-08-20 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_app", "0002_currencydirectory_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencyexchangeratedirectory",
            options={
                "verbose_name": "Справочник курсы валют",
                "verbose_name_plural": "Справочники курсов валют",
            },
        ),
        migrations.RenameField(
            model_name="currencydirectory",
            old_name="char_code",
            new_name="CharCode",
        ),
        migrations.RenameField(
            model_name="currencydirectory",
            old_name="name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="currencydirectory",
            old_name="value",
            new_name="Value",
        ),
        migrations.RenameField(
            model_name="currencyexchangeratedirectory",
            old_name="currency",
            new_name="Currency",
        ),
        migrations.RenameField(
            model_name="currencyexchangeratedirectory",
            old_name="date",
            new_name="Date",
        ),
    ]
