# Generated by Django 4.2.4 on 2023-08-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_app", "0003_alter_currencyexchangeratedirectory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencydirectory",
            name="CharCode",
            field=models.CharField(max_length=5, verbose_name="Символьное обозначение"),
        ),
        migrations.AlterField(
            model_name="currencydirectory",
            name="Name",
            field=models.CharField(max_length=90, verbose_name="Наименование"),
        ),
    ]
