# Generated by Django 4.2.4 on 2023-08-20 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_app", "0004_alter_currencydirectory_charcode_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="currencyexchangeratedirectory",
            unique_together={("Date", "Currency")},
        ),
    ]
